### ISSUE TITLE
Hello Denis!!!

### ISSUE THREAD

**Issue by zany99** [zany99/Hello-World#3]
What color would you like to have the background of our site?

**Comment by zany99** [comment]
>

**Comment by Denys609** [comment]
Black and white. 
![depositphotos_30528953-stock-illustration-modern-black-and-white-wallpaper](https://user-images.githubusercontent.com/38349801/40500733-595a36c0-5f8e-11e8-851f-7e3c47e00193.jpg)

**Comment by zany99** [comment]
Okey! It is good idea %)
